### PR TITLE
fix fetching skylib repo by changing to latest commit

### PR DESCRIPTION
**Pull request by natansil**

### CODE REVIEW

**Comment by ittaiz** [comment]
Test this please (ci bot)

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ittaiz** [comment]
test this please (ci bot)

**Comment by ittaiz** [comment]
good news it passed. bad news we have serious flakiness issues...

**Pull request merged**
