### PR TITLE
Windows: tests work with native test wrapper

### PR DESCRIPTION
**Pull request by laszlocsomor**
See https://github.com/bazelbuild/bazel/issues/6622

### CODE REVIEW

**Comment by laszlocsomor** [comment]
("WIP" until I fix all tests.)

**Comment by laszlocsomor** [comment]
Tests were failing because the inner Bazel's `ABSOLUTE_JAVABASE` path was near the `MAX_PATH` (260) limit on Windows. The tests classes' names are part of those paths, so renaming the test classes to a shorter name is one (albeit ugly) solution.

I'll look for a nicer solution now.

**Comment by laszlocsomor** [comment]
After a few hours of failed attempts, I gave up and just renamed the test classes to shorter names.

**Comment by achew22** [comment]
@iirina is the biggest user of the java part of the repo. Could you pull this PR into your repo and say if it causes issues?

**Comment by laszlocsomor** [comment]
ping @iirina

**Comment by iirina** [comment]
The PR looks good to me and the tests pass, so feel free to continue with the review.

**Comment by laszlocsomor** [comment]
ping -- @achew22 , @ittaiz : does this LGTY?

**Comment by achew22** [comment]
@laszlocsomor it feels very strange to me that the classes are going to get abbreviated in order to satisfy the naming requirements of Windows. Is this only exposed because Bazel has prefixed a huge number of characters in the prefix of the file?

**Comment by laszlocsomor** [comment]
Yes and yes. Also because the prefix is doubled: once for the outer and once for the inner Bazel.

There's no rush though -- contrary to my plans, I can't enable this feature in Bazel 0.27.

**Comment by achew22** [comment]
@laszlocsomor thanks for the quick response. Are there any plans to alleviate the XX character limit in a more general way? My concerns here revolve around the fact that if you were depending on Bazel Integration Testing in your repo, you would end up with the additional prefix of `build_bazel_integration_testing` (31 characters) in the file path, and I don't think it is possible to remove 31 characters from the classpath in here without seriously impeding readability.

I'm trying it on `build.bazel.tests.integration.BazelBaseTestCase` (47 characters), I assume that the domain has to be valid and owned, so `build.bazel` is a must. Given that constraint even `build.bazel.t.i.BBTC` is 51 characters and the illegibility of that would even make a Golang developer cringe!

Maybe now is a good time to take a step back and decide if there is a better solution maybe. I would be happy to schedule a meeting to talk it over with you internally, my @google.com email should be pretty easy to figure out and I'm happy to meet during EMEA friendly times.

PS: Thanks so much for caring about this project and putting in so much effort, I really appreciate it.

**Comment by laszlocsomor** [comment]
To follow up, this PR is now obsolete: turns out the bug was in the test wrapper. See https://github.com/bazelbuild/bazel-integration-testing/issues/148

**Pull request closed without merging**
