### PR TITLE
Fix Bazel incompatible changes

### PR DESCRIPTION
**Pull request by achew22**
The output from `bazelisk --migrate build //...`

```
Command was successful with the following flags:
  --incompatible_bzl_disallow_load_after_statement
  --incompatible_disable_deprecated_attr_params
  --incompatible_disable_expand_if_all_available_in_flag_set
  --incompatible_disable_genrule_cc_toolchain_dependency
  --incompatible_disable_legacy_cc_provider
  --incompatible_disable_legacy_proto_provider
  --incompatible_disable_proto_source_root
  --incompatible_disable_runtimes_filegroups
  --incompatible_disallow_data_transition
  --incompatible_disallow_dict_plus
  --incompatible_disallow_filetype
  --incompatible_disallow_load_labels_to_cross_package_boundaries
  --incompatible_disallow_old_style_args_add
  --incompatible_dont_emit_static_libgcc
  --incompatible_expand_directories
  --incompatible_linkopts_in_user_link_flags
  --incompatible_merge_genfiles_directory
  --incompatible_new_actions_api
  --incompatible_no_support_tools_in_action_inputs
  --incompatible_remove_native_maven_jar
  --incompatible_require_feature_configuration_for_pic
  --incompatible_strict_argument_ordering
  --incompatible_use_aapt2_by_default

Migration is needed for the following flags:
  --incompatible_no_transitive_loads
```

Fixes: #104

### CODE REVIEW

**Comment by achew22** [comment]
@laurentlb, I believe this fixes the incompatible issues.

**Comment by ittaiz** [comment]
Can you please merge master in?

**Comment by achew22** [comment]
@ittaiz I don't have permission to merge. Can you add me as an admin on the repo?

**Comment by ittaiz** [comment]
done.
thought codeowners will give it to you

**Comment by achew22** [comment]
@ittaiz, are you comfortable with me having merge powers on the repo? If so, can you grant it to me or leave a comment that says you're okay with that and I'll find a Bazel admin who can grant it for me

**Comment by ittaiz** [comment]
I am. I think I wasn’t clear before, I also gave you merge powers.

**Comment by achew22** [comment]
Oh, perfect. Thanks!

**Comment by ittaiz** [comment]
Thank you for chipping in. This library is important to me but it seems I
have too many things on my plate now (we are in the final stages of moving
all of Wix’s ~250 backend developers to a new CI system based on Bazel).
I hope to have more capacity in the medium term.

**Pull request merged**
