### PR TITLE
Use print() function in both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
__print()__ is a function in Python 3.

### CODE REVIEW

**Comment by ittaiz** [comment]
go code is failing but I think it's irrelevant. Opening a dummy commit now to verify

**Comment by ittaiz** [comment]
indeed. https://github.com/bazelbuild/bazel-integration-testing/pull/98
@jayconrod , @achew22 any chance you can lend a hand and see why rules_go support is failing on master? (see the linked dummy commit)

**Comment by jayconrod** [comment]
@ittaiz It looks like you're using Bazel 0.20 with an older version of rules_go. Bazel 0.20 deprecated an API an that rules_go used to get C compiler information for cgo. You should be able to work around this temporarily with `--noincompatible_disable_legacy_cpp_toolchain_skylark_api`, but the API may be completely removed as soon as 0.21.

rules_go now gets information from the new `cc_common` API. That change has been backported to releases after October 16 (so 0.14.3, 0.15.5, and 0.16.0 will all have that update). I don't think there have been any breaking changes since 0.13.0, so hopefully the upgrade will be smooth.

Here's the error message:

```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ba5e8af554489a4ee1ea4e47c1970ef4/external/io_bazel_rules_go/BUILD.bazel:18:1: in go_context_data rule @io_bazel_rules_go//:go_context_data:
Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ba5e8af554489a4ee1ea4e47c1970ef4/external/io_bazel_rules_go/BUILD.bazel", line 18
		go_context_data(name = 'go_context_data')
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ba5e8af554489a4ee1ea4e47c1970ef4/external/io_bazel_rules_go/go/private/context.bzl", line 300, in _go_context_data
		_filter_options((cpp.compiler_options(features) ...)), ...)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ba5e8af554489a4ee1ea4e47c1970ef4/external/io_bazel_rules_go/go/private/context.bzl", line 301, in _filter_options
		cpp.compiler_options(features)
Information about the C++ toolchain API is not accessible anymore through ctx.fragments.cpp (see --incompatible_disable_legacy_cpp_toolchain_skylark_api on http://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disable-legacy-c-configuration-api for migration notes). Use CcToolchainInfo instead.
```

**Comment by ittaiz** [comment]
Hi, master is fixed. Can you please rebase?

**Comment by cclauss** [comment]
Still broken.

**Comment by ittaiz** [comment]
Thanks!

**Pull request merged**
