### PR TITLE
Reverting "support running tools/bazel script in java integration tests" to fix master

### PR DESCRIPTION
**Pull request by ittaiz**

### CODE REVIEW

**Comment by ittaiz** [comment]
@philwo I can safely remove `ci.bazel.build` as a required check, right?
fixes #25 cc @buchgr

**Comment by ittaiz** [comment]
@natansil it's indeed your change :( I guess there's a difference between what you ran and what the ci runs. I suggest you re-submit your change and see the failures on buildkite (once @philwo will send you an invite to buildkite)

**Comment by natansil** [comment]
@ittaiz opened a new PR.
waiting for phillip's email address in DM

**Comment by philwo** [comment]
> @philwo I can safely remove ci.bazel.build as a required check, right?

Yes, this can be removed. I've already removed the webhooks, so in theory it should no longer show up for new PRs.

**Pull request merged**
