### PR TITLE
support running tools/bazel script in java integration tests (2nd attempt)

### PR DESCRIPTION
**Pull request by natansil**

### CODE REVIEW

**Comment by ittaiz** [comment]
@philwo two strange issues:
1. I don’t have “details” link next to verify
2. When clicking on details of the buildkite step I get to a 404
I’d appreciate your help in understanding what went wrong

**Comment by philwo** [comment]
@ittaiz We yesterday fixed a configuration issue in our Buildkite setup and merged the two separate presubmit and postsubmit pipelines (or rather: dropped the "postsubmit" suffix of that pipeline and deleted the separate "presubmit" pipeline). Now everything is fine, but it caused a one-time disruption: Presubmits that were still on the old pipeline got deleted.

If you rerun the presubmit checks by modifying this commit somehow (I think clicking the "Update branch" button next to "This branch is out-of-date with the base branch" should be enough), it should just work.

Sorry! It won't happen again.

**Comment by ittaiz** [comment]
I approve the contribution

**Comment by ittaiz** [comment]
@philwo now it's failed due to:
``

FileNotFoundError: [Errno 2] No such file or directory: '.bazelci/presubmit.yml'
--
  | [2018-03-01T06:58:52Z] 2018-03-01 06:58:52 FATAL  Config file is empty


```
We have that file and it's not empty

**Comment by philwo** [comment]
@ittaiz Looks like the config file wasn't present when this pull request was branched - Buildkite takes the config file from the actual commit. If you "Update branch" it should work :)

**Comment by ittaiz** [comment]
I see. thanks.
"Update branch" will create a merge commit so I'd rather not.
@natansil can you take a 3rd stab at it this time, rebasing on top of master before you create the PR?

**Comment by philwo** [comment]
Out of curiosity: Would it matter that there’s a merge commit in this PR if you use “Squash and merge” or “Rebase and merge” modes to merge the PR? It should disappear from the history then, I guess?

(We’re trying to find good GitHub workflows that we can recommend to contributors and repo owners and are collecting experiences of others :))

**Comment by ittaiz** [comment]
I vaguely remember having a bad experience with it. Probably worth trying
it out on a dummy repo and seeing how the history on master looks afterwards

**Comment by philwo** [comment]
I’ll try it out and write up my findings for our docs! :) Will ping you on the commit.

**Pull request closed without merging**
