### PR TITLE
Remove the go form of integration testing

### PR DESCRIPTION
**Pull request by achew22**
rules_go provides a better way to approach this problem.

### CODE REVIEW

**Comment by achew22** [comment]
@jayconrod @ittaiz since `rules_go` provides a separate and better framework for doing this, I propose we remove the go section of this repo.

**Comment by ittaiz** [comment]
That didn’t help. Any thoughts what to do about the CLA check?

**Comment by achew22** [comment]
@jayconrod, could you please poke the cla bot next time you're at your work computer

**Comment by ittaiz** [comment]
wdyt about the link (readme or here) to the recommended way for go users?

**Comment by achew22** [comment]
Did you look at the change? It has links and recommendations for what to do already in the PR

**Comment by ittaiz** [comment]
Feel free to merge when the CLA is fixed

**Comment by jayconrod** [comment]
Not sure what's going on with the CLA. I'm guessing that GitHub sent a webhook request when a new commit was added and never got a response.

I'll try removing the cla label and pinging the bot. If that doesn't work, I'll open a bug internally.

**Comment by jayconrod** [comment]
Seems to have worked. @achew22 Thanks for updating this!

**Pull request merged**
