### PR TITLE
Use canonical version checking from Skylib

### PR DESCRIPTION
**Pull request by jin**
Fixes https://github.com/bazelbuild/bazel/issues/4423

### CODE REVIEW

**Comment by achew22** [comment]
I approve, but it appears my approval may not be enough.

**Comment by achew22** [comment]
@damienmg I've noticed the "ci.bazel.io - bazel-integration-testing — Waiting for status to be reported" message but no link to details and a different "build finished" version up on a couple of repos. Do you know what's up with that?

**Comment by jin** [comment]
@achew22 the CI has been moved to ci.bazel.build, maybe there's a redirect from .io to .build that's messing the error reporting.

**Comment by achew22** [comment]
Ooh, good eyes! That's totally it. Someone with admin in the repo needs to go in and change ci.bazel.io to not be required in favor of ci.bazel.build.

**Comment by achew22** [comment]
For the person wich such power https://github.com/bazelbuild/bazel-integration-testing/settings/branches/master is where you would do that.

**Comment by damienmg** [comment]
This was the required check that changed as a consequence for the rename. Fixed.

**Pull request merged**
