### PR TITLE
added branch scoping to buildkite build badge

### PR DESCRIPTION
**Pull request by ittaiz**
currently it will show failing if any PR is failing.
Scoping it to master

### CODE REVIEW

**Comment by philwo** [comment]
@buchgr Why aren’t there any ResultStore links here for Ubuntu 14.04 and Ubuntu 16.04?

Also, weren’t the build badge supposed to somehow automatically only care about master?

**Comment by ittaiz** [comment]
re automatically- from [buildkite settings](https://buildkite.com/bazel/bazel-integration-testing/settings/badges): "Show off your pipeline’s last build status with a build status badge. Adding a branch param will scope it to a particular branch (e.g. ?branch=master)"

**Comment by philwo** [comment]
Ahh, I see - thanks! We’ll update the build badges in all bazelbuild repos then.

**Comment by ittaiz** [comment]
great, any chance you can approve the PR?

BTW, bazel's build badge is completely down (points to ci.bazel.build)

**Comment by ittaiz** [comment]
@philwo any objections to merging? if not can you approve this?

**Pull request merged**
