### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by jchv**
WIP. Depends on the update to `rules_go` in #95.

Java tests are failing quietly, I can't find any relevant logs yet.

### CODE REVIEW

**Comment by achew22** [comment]
@jchv it might be worth patching in https://github.com/bazelbuild/bazel-integration-testing/pull/94 so that you can get buildkite to build for windows as well which may provide some useful feedback

**Comment by jchv** [comment]
> @jchv it might be worth patching in #94 so that you can get buildkite to build for windows as well which may provide some useful feedback

Good idea. Almost all of the changes in that PR would conflict with mine, so I just copied the presubmit.yml changes for now.

**Comment by ittaiz** [comment]
Well done!
This repo currently works on RBE and it's paramount we keep it like this. I'll try today/tomorrow to get #83 to pass so you'll be able to rebase off of that.

**Comment by meteorcloudy** [comment]
@jchv Are you still working on this? Is there anything we can do to help?

**Comment by jchv** [comment]
Ah, yeah, I am. I'm a bit confused as to what to do with the RBE support, however.

**Comment by achew22** [comment]
@jchv, according to the [presubmit definition](https://github.com/bazelbuild/bazel-integration-testing/blob/master/.bazelci/presubmit.yml), this repo doesn't test against RBE and https://github.com/bazelbuild/bazel-integration-testing/pull/103 which adds it seems to be stalled. @ittaiz if you have more information on that we should take it into consideration but my plan is to merge this if we get the windows tests passing. Hopefully there won't be too much toe stomping.

**Comment by ittaiz** [comment]
Is this still alive?

**Comment by meteorcloudy** [comment]
We can close this one since Windows support is added at https://github.com/bazelbuild/bazel-integration-testing/pull/117

**Comment by jchv** [comment]
Sorry about that! Forgot to close it when it was superceded.

**Pull request closed without merging**
