### PR TITLE
support running tools/bazel script in java integration tests

### PR DESCRIPTION
**Pull request by natansil**
@damienmg @ittaiz please review.
The local tests pass and also the tests that rely on this change also pass

### CODE REVIEW

**Comment by ittaiz** [comment]
@philwo any idea why the build is stuck for a few good hours?

**Comment by philwo** [comment]
Jenkins is probably already half dead by now - all we could do is reboot some VMs and hope for the best, but...

@buchgr Didn’t we enable presubmit checks for this repo? At least for Linux it should be fine, right, even if it takes a long time to test?

**Comment by ittaiz** [comment]
Why should it take a long time? :(

**Comment by ittaiz** [comment]
I'm merging after I saw it pass locally.
@philwo this is the second time I had to do this... We really need to solve this

**Pull request merged**
